# Generated by Django 6.0 on 2026-03-10 12:21

import django.core.validators
import django.db.models.deletion
import login.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (в монетах)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Изображение')),
                ('quantity', models.PositiveIntegerField(default=10, verbose_name='Остаток на складе')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
                ('item_type', models.CharField(choices=[('cosmetic', 'Косметика (Для всех)'), ('merch', 'Мерч (Только для топ рейтинга)'), ('frame', 'Рамка для аватара')], default='cosmetic', max_length=10, verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары в магазине',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования для получения')),
                ('icon', models.ImageField(upload_to=login.models.achievement_icon_upload_to, verbose_name='Иконка (PNG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал педагог')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы (класса)')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор (педагог)')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('price_at_moment', models.PositiveIntegerField(verbose_name='Цена на момент покупки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выдачи'), ('completed', 'Выдано')], default='pending', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.shopitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'История покупок',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Педагог')], max_length=10, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('rating_points', models.PositiveIntegerField(default=0, verbose_name='Рейтинговые очки')),
                ('artel', models.CharField(blank=True, choices=[('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4'), ('Artel 5', 'Артель 5')], max_length=20, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, verbose_name='Звание')),
                ('volunteering_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Волонтёрство')),
                ('contests_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Конкурсы')),
                ('academic_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Учебная активность')),
                ('extracurricular_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Внеучебная активность')),
                ('projects_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Проектная деятельность')),
                ('active_frame', models.ForeignKey(blank=True, limit_choices_to={'item_type': 'frame'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_wearing', to='login.shopitem', verbose_name='Активная рамка')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='login.group', verbose_name='Группа (класс)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='DisplayedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayed_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отображаемое достижение',
                'verbose_name_plural': 'Отображаемые достижения',
                'ordering': ['display_order', 'achievement__name'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='login.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
