# Generated by Django 5.2.7 on 2025-10-31 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Педагог')], max_length=10, verbose_name='Роль')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('rating_points', models.PositiveIntegerField(default=0, verbose_name='Рейтинговые очки')),
                ('group_name', models.CharField(blank=True, max_length=50, verbose_name='Группа (класс)')),
                ('artel', models.CharField(blank=True, max_length=100, verbose_name='Артель')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Звание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
