# Generated by Django 5.2.8 on 2026-03-10 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Например: can_award_points', max_length=100, unique=True, verbose_name='Кодовое имя')),
                ('name', models.CharField(max_length=200, verbose_name='Читаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор (педагог)'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым — доступно всем', related_name='available_items', to='login.role', verbose_name='Доступно ролям'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.permission', verbose_name='Право')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Право роли',
                'verbose_name_plural': 'Права ролей',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='login.RolePermission', to='login.permission', verbose_name='Права'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile', verbose_name='Профиль')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'unique_together': {('profile', 'role')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='login.UserRole', to='login.role', verbose_name='Роли'),
        ),
    ]
