# Generated by Django 5.2.7 on 2025-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userprofile_group_name_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки: Учебная активность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contests_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки: Конкурсы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extracurricular_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки: Внеучебная активность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки: Проектная деятельность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volunteering_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки: Волонтёрство'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Звание'),
        ),
    ]
