# Generated by Django 5.2.8 on 2025-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userprofile_academic_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='artel',
            field=models.CharField(choices=[('None', 'Без артеля'), ('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4')], default='None', max_length=20),
        ),
    ]
