# Generated by Django 5.2.8 on 2025-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userprofile_artel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='artel',
            field=models.CharField(choices=[('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4')], max_length=20),
        ),
    ]
