# Generated by Django 5.2.8 on 2025-11-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_achievement_displayedachievement_userachievement'),
        ('login', '0006_alter_userprofile_artel'),
    ]

    operations = [
    ]
