# Generated by Django 5.2.8 on 2025-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_shopcategory_shopitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('cosmetic', 'Косметика (Для всех)'), ('merch', 'Мерч (Только для топ рейтинга)')], default='cosmetic', max_length=10, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='artel',
            field=models.CharField(blank=True, choices=[('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4'), ('Artel 5', 'Артель 5')], max_length=20, null=True),
        ),
    ]
