# Generated by Django 5.2.8 on 2025-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_shopitem_item_type_alter_userprofile_artel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='Остаток на складе'),
        ),
    ]
