# Generated by Django 5.2.8 on 2026-01-09 12:10

import django.db.models.deletion
import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_shopitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='category',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает выдачи'), ('completed', 'Выдано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_frame',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'frame'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_wearing', to='login.shopitem', verbose_name='Активная рамка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to=login.models.achievement_icon_upload_to, verbose_name='Иконка (PNG)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('cosmetic', 'Косметика (Для всех)'), ('merch', 'Мерч (Только для топ рейтинга)'), ('frame', 'Рамка для аватара')], default='cosmetic', max_length=10, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='artel',
            field=models.CharField(blank=True, choices=[('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
