# Generated by Django 5.2.8 on 2026-01-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_shopitem_category_purchase_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='artel',
            field=models.CharField(blank=True, choices=[('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4'), ('Artel 5', 'Артель 5')], max_length=20, null=True),
        ),
    ]
