# Generated by Django 5.2.8 on 2026-04-03 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы (класса)')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор (педагог)')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('rating_points', models.PositiveIntegerField(default=0, verbose_name='Рейтинговые очки')),
                ('artel', models.CharField(blank=True, choices=[('Artel 1', 'Артель 1'), ('Artel 2', 'Артель 2'), ('Artel 3', 'Артель 3'), ('Artel 4', 'Артель 4'), ('Artel 5', 'Артель 5')], max_length=20, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, verbose_name='Звание')),
                ('volunteering_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Волонтёрство')),
                ('contests_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Конкурсы')),
                ('academic_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Учебная активность')),
                ('extracurricular_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Внеучебная активность')),
                ('projects_points', models.PositiveIntegerField(default=0, verbose_name='Очки: Проектная деятельность')),
                ('active_frame', models.ForeignKey(blank=True, limit_choices_to={'item_type': 'frame'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_wearing', to='shop.shopitem', verbose_name='Активная рамка')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='profile_app.group', verbose_name='Группа (класс)')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', through='login.UserRole', to='login.role', verbose_name='Роли')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
