# Generated by Django 5.2.8 on 2026-04-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (в монетах)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Изображение')),
                ('quantity', models.PositiveIntegerField(default=10, verbose_name='Остаток на складе')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
                ('item_type', models.CharField(choices=[('cosmetic', 'Косметика (Для всех)'), ('merch', 'Мерч (Только для топ рейтинга)'), ('frame', 'Рамка для аватара')], default='cosmetic', max_length=10, verbose_name='Тип товара')),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Оставьте пустым — доступно всем', related_name='available_items', to='login.role', verbose_name='Доступно ролям')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары в магазине',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('price_at_moment', models.PositiveIntegerField(verbose_name='Цена на момент покупки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выдачи'), ('completed', 'Выдано')], default='pending', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'История покупок',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
